### PR TITLE
Update the API endpoints

### LINKED ISSUE #7: It's broken
:disappointed: Looks like the request to the raw GitHub url is failing.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37347245-it-s-broken?utm_campaign=plugin&utm_content=tracker%2F3795745&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F3795745&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by IonicaBizau**
Fixes #7.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@frissdiegurke And don't forget to publish the new version on npm. :grin:

**Comment by frissdiegurke** [comment]
Already did ;-) `v0.1.2`

**Comment by frissdiegurke** [comment]
Thanks for fixing :+1:

**Comment by IonicaBizau** [comment]
No worries! After few months I restarted my Node.js process which powers my website.
I saw that warning in the output and there were no emojis in the browser, so I had to do it quickly. :grin:

**Pull request merged**
